# Generated by Django 3.1.1 on 2020-09-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='image',
            field=models.ImageField(upload_to='burgers'),
        ),
    ]
